const express = require('express');
const router = express.Router();
const {
  searchProviders,
  getFeatured,
  getUrgent,
  getBySlug,
  getCategories,
} = require('../controllers/searchcontroller');
const { optionalAuth } = require('../middlewares/authmiddleware');

router.get('/featured', getFeatured);
router.get('/urgent', getUrgent);
router.get('/categories', getCategories);
router.get('/by-slug/:slug', getBySlug);
router.get('/providers', optionalAuth, searchProviders);

router.get('/seed-categories', async (req, res) => {
  try {
    const ServiceCategory = require('../models/servicecategory');
    const newCats = [
      { name: 'Médico a domicilio', slug: 'medico', icon: '🩺', subcategories: [{ name: 'Clínica general', slug: 'clinica-general' }, { name: 'Pediatría', slug: 'pediatria' }, { name: 'Geriatría', slug: 'geriatria' }], active: true },
      { name: 'Dentista', slug: 'dentista', icon: '🦷', subcategories: [{ name: 'Limpieza dental', slug: 'limpieza-dental' }, { name: 'Ortodoncia', slug: 'ortodoncia' }, { name: 'Blanqueamiento', slug: 'blanqueamiento' }], active: true },
      { name: 'Enfermero', slug: 'enfermero', icon: '💉', subcategories: [{ name: 'Cuidado domiciliario', slug: 'cuidado-domiciliario' }, { name: 'Inyecciones y curaciones', slug: 'inyecciones-curaciones' }], active: true },
      { name: 'Masajista', slug: 'masajista', icon: '💆', subcategories: [{ name: 'Masaje relajante', slug: 'masaje-relajante' }, { name: 'Masaje deportivo', slug: 'masaje-deportivo' }, { name: 'Reflexología', slug: 'reflexologia' }], active: true },
      { name: 'Maquillador', slug: 'maquillador', icon: '💄', subcategories: [{ name: 'Maquillaje social', slug: 'maquillaje-social' }, { name: 'Maquillaje artístico', slug: 'maquillaje-artistico' }, { name: 'Maquillaje de novia', slug: 'maquillaje-novia' }], active: true },
      { name: 'Cuidado de adultos mayores', slug: 'cuidado-adultos', icon: '🤝', subcategories: [{ name: 'Acompañante terapéutico', slug: 'acompanante-terapeutico' }, { name: 'Cuidador nocturno', slug: 'cuidador-nocturno' }], active: true },
      { name: 'Niñera / Babysitter', slug: 'ninera', icon: '👶', subcategories: [{ name: 'Cuidado diurno', slug: 'cuidado-diurno' }, { name: 'Cuidado nocturno', slug: 'cuidado-nocturno' }, { name: 'Estimulación temprana', slug: 'estimulacion-temprana' }], active: true },
      { name: 'Veterinario', slug: 'veterinaria', icon: '🐾', subcategories: [{ name: 'Consulta a domicilio', slug: 'consulta-domicilio-vet' }, { name: 'Vacunación', slug: 'vacunacion' }, { name: 'Peluquería canina', slug: 'peluqueria-canina' }], active: true },
      { name: 'Paseador de perros', slug: 'paseador', icon: '🐕', subcategories: [{ name: 'Paseo individual', slug: 'paseo-individual' }, { name: 'Paseo grupal', slug: 'paseo-grupal' }], active: true },
      { name: 'Guardería de mascotas', slug: 'guarderia-mascotas', icon: '🐩', subcategories: [{ name: 'Hospedaje canino', slug: 'hospedaje-canino' }, { name: 'Guardería felina', slug: 'guarderia-felina' }], active: true },
      { name: 'Adiestramiento canino', slug: 'adiestramiento', icon: '🦴', subcategories: [{ name: 'Obediencia básica', slug: 'obediencia-basica' }, { name: 'Corrección de conducta', slug: 'correccion-conducta' }], active: true },
      { name: 'Seguridad privada', slug: 'seguridad', icon: '🔒', subcategories: [{ name: 'Vigilancia de eventos', slug: 'vigilancia-eventos' }, { name: 'Portería y custodia', slug: 'porteria-custodia' }], active: true },
      { name: 'Alarmas y CCTV', slug: 'alarmas', icon: '📹', subcategories: [{ name: 'Instalación de cámaras', slug: 'instalacion-camaras' }, { name: 'Alarmas perimetrales', slug: 'alarmas-perimetrales' }], active: true },
      { name: 'Soldador', slug: 'soldador', icon: '🔧', subcategories: [{ name: 'Soldadura MIG/TIG', slug: 'soldadura-mig-tig' }, { name: 'Estructuras metálicas', slug: 'estructuras-metal' }], active: true },
      { name: 'Techista / Impermeabilización', slug: 'techista', icon: '🏠', subcategories: [{ name: 'Techos de chapa', slug: 'techos-chapa' }, { name: 'Membrana asfáltica', slug: 'membrana-asfaltica' }, { name: 'Techo de tejas', slug: 'techo-tejas' }], active: true },
      { name: 'Fletes', slug: 'fletes', icon: '🚛', subcategories: [{ name: 'Flete pequeño', slug: 'flete-pequeno' }, { name: 'Flete grande', slug: 'flete-grande' }, { name: 'Transporte de maquinaria', slug: 'transporte-maquinaria' }], active: true },
      { name: 'Delivery y mensajería', slug: 'delivery', icon: '📦', subcategories: [{ name: 'Mensajería en moto', slug: 'mensajeria-moto' }, { name: 'Delivery de comida', slug: 'delivery-comida' }], active: true },
      { name: 'Organizador de eventos', slug: 'eventos', icon: '🎪', subcategories: [{ name: 'Fiestas infantiles', slug: 'fiestas-infantiles' }, { name: 'Casamientos', slug: 'casamientos' }, { name: 'Eventos corporativos', slug: 'eventos-corporativos' }], active: true },
      { name: 'Animador infantil', slug: 'animador', icon: '🤹', subcategories: [{ name: 'Payaso', slug: 'payaso' }, { name: 'Mago', slug: 'mago' }, { name: 'Show de personajes', slug: 'show-personajes' }], active: true },
      { name: 'Fotógrafo de eventos', slug: 'fotografo-eventos', icon: '📸', subcategories: [{ name: 'Casamientos', slug: 'foto-casamientos' }, { name: 'Quinceañeros', slug: 'quinceaneros' }, { name: 'Cumpleaños', slug: 'foto-cumpleanos' }], active: true },
      { name: 'Camarógrafo', slug: 'camarografo', icon: '🎬', subcategories: [{ name: 'Video de bodas', slug: 'video-bodas' }, { name: 'Producción audiovisual', slug: 'produccion-audiovisual' }], active: true },
      { name: 'Bartender', slug: 'bartender', icon: '🍸', subcategories: [{ name: 'Bar móvil', slug: 'bar-movil' }, { name: 'Coctelería', slug: 'cocteleria' }], active: true },
      { name: 'Mozo / Camarero', slug: 'mozo', icon: '🍽️', subcategories: [{ name: 'Eventos y fiestas', slug: 'eventos-camarero' }, { name: 'Catering', slug: 'catering-mozo' }], active: true },
      { name: 'Repostería y pastelería', slug: 'reposteria', icon: '🎂', subcategories: [{ name: 'Tortas personalizadas', slug: 'tortas-personalizadas' }, { name: 'Cupcakes y macarons', slug: 'cupcakes' }, { name: 'Catering dulce', slug: 'catering-dulce' }], active: true },
      { name: 'Personal trainer', slug: 'trainer', icon: '🏋️', subcategories: [{ name: 'Entrenamiento a domicilio', slug: 'entrenamiento-domicilio' }, { name: 'Musculación', slug: 'musculacion' }, { name: 'Funcional', slug: 'funcional' }], active: true },
      { name: 'Profesor de yoga', slug: 'yoga', icon: '🧘', subcategories: [{ name: 'Yoga para principiantes', slug: 'yoga-principiantes' }, { name: 'Meditación', slug: 'meditacion' }], active: true },
      { name: 'Profesor de pilates', slug: 'pilates', icon: '🤸', subcategories: [{ name: 'Pilates mat', slug: 'pilates-mat' }, { name: 'Pilates reformer', slug: 'pilates-reformer' }], active: true },
      { name: 'Instructor de natación', slug: 'natacion', icon: '🏊', subcategories: [{ name: 'Clases para adultos', slug: 'natacion-adultos' }, { name: 'Clases para niños', slug: 'natacion-ninos' }], active: true },
      { name: 'Profesor de idiomas', slug: 'idiomas', icon: '🌍', subcategories: [{ name: 'Inglés', slug: 'ingles-idioma' }, { name: 'Portugués', slug: 'portugues-idioma' }, { name: 'Francés', slug: 'frances-idioma' }], active: true },
      { name: 'Tutor académico', slug: 'tutor', icon: '📖', subcategories: [{ name: 'Secundaria', slug: 'tutor-secundaria' }, { name: 'Universidad', slug: 'tutor-universidad' }, { name: 'Ingreso universitario', slug: 'ingreso-universitario' }], active: true },
      { name: 'Clases de manejo', slug: 'manejo', icon: '🚗', subcategories: [{ name: 'Auto', slug: 'clases-auto' }, { name: 'Moto', slug: 'clases-moto' }], active: true },
      { name: 'Reparación de electrodomésticos', slug: 'electrodomesticos', icon: '🔌', subcategories: [{ name: 'Lavarropas', slug: 'lavarropas' }, { name: 'Heladera', slug: 'heladera' }, { name: 'Microondas y hornos', slug: 'microondas-hornos' }], active: true },
      { name: 'Instalación de gas envasado', slug: 'gas-envasado', icon: '🫙', subcategories: [{ name: 'Conexión de garrafas', slug: 'conexion-garrafas' }, { name: 'Instalación de tubos', slug: 'instalacion-tubos' }], active: true },
      { name: 'Pintura automotor', slug: 'pintura-auto', icon: '🚙', subcategories: [{ name: 'Chapa y pintura', slug: 'chapa-pintura' }, { name: 'Pulido y encerado', slug: 'pulido-encerado' }], active: true },
      { name: 'Lavado de autos', slug: 'lavado-autos', icon: '🚿', subcategories: [{ name: 'Lavado exterior', slug: 'lavado-exterior' }, { name: 'Lavado interior', slug: 'lavado-interior' }, { name: 'Detailing', slug: 'detailing' }], active: true },
      { name: 'Instalación de pisos', slug: 'pisos', icon: '🪵', subcategories: [{ name: 'Porcelanato', slug: 'porcelanato' }, { name: 'Madera y laminado', slug: 'madera-laminado' }, { name: 'Microcemento', slug: 'microcemento' }], active: true },
      { name: 'Colocación de cerámicos', slug: 'ceramicos', icon: '🧱', subcategories: [{ name: 'Baños y cocinas', slug: 'banos-cocinas' }, { name: 'Exteriores', slug: 'ceramicos-exteriores' }], active: true },
      { name: 'Instalación de aberturas', slug: 'aberturas', icon: '🚪', subcategories: [{ name: 'Puertas', slug: 'instalacion-puertas' }, { name: 'Ventanas', slug: 'instalacion-ventanas' }, { name: 'Persianas y cortinas', slug: 'persianas-cortinas' }], active: true },
      { name: 'Cortinas y persianas', slug: 'cortinas', icon: '🪟', subcategories: [{ name: 'Cortinas a medida', slug: 'cortinas-medida' }, { name: 'Roller y bandas verticales', slug: 'roller-bandas' }], active: true },
      { name: 'Decoración de interiores', slug: 'decoracion', icon: '🛋️', subcategories: [{ name: 'Asesoría de decoración', slug: 'asesoria-decoracion' }, { name: 'Home staging', slug: 'home-staging' }], active: true },
      { name: 'Mudanzas internacionales', slug: 'mudanzas-internacionales', icon: '✈️', subcategories: [{ name: 'Aduanas y trámites', slug: 'aduanas' }, { name: 'Embalaje internacional', slug: 'embalaje-internacional' }], active: true },
      { name: 'Cerrajero automotor', slug: 'cerrajero-auto', icon: '🔐', subcategories: [{ name: 'Apertura de autos', slug: 'apertura-autos' }, { name: 'Duplicado de llaves', slug: 'duplicado-llaves' }], active: true },
      { name: 'Técnico en refrigeración', slug: 'refrigeracion', icon: '🌡️', subcategories: [{ name: 'Heladeras comerciales', slug: 'heladeras-comerciales' }, { name: 'Cámaras frigoríficas', slug: 'camaras-frigorificas' }], active: true },
      { name: 'Instalación solar', slug: 'solar', icon: '☀️', subcategories: [{ name: 'Paneles solares', slug: 'paneles-solares' }, { name: 'Calefón solar', slug: 'calefon-solar' }], active: true },
      { name: 'Plomería industrial', slug: 'plomeria-industrial', icon: '🏭', subcategories: [{ name: 'Instalaciones industriales', slug: 'instalaciones-industriales' }, { name: 'Mantenimiento fabril', slug: 'mantenimiento-fabril' }], active: true },
      { name: 'Electricidad industrial', slug: 'electricidad-industrial', icon: '⚙️', subcategories: [{ name: 'Tableros industriales', slug: 'tableros-industriales' }, { name: 'Automatización', slug: 'automatizacion' }], active: true },
      { name: 'Servicio de limpieza industrial', slug: 'limpieza-industrial', icon: '🏗️', subcategories: [{ name: 'Limpieza de fábricas', slug: 'limpieza-fabricas' }, { name: 'Limpieza de tanques', slug: 'limpieza-tanques' }], active: true },
      { name: 'Gestor / Trámites', slug: 'gestor', icon: '📋', subcategories: [{ name: 'Trámites municipales', slug: 'tramites-municipales' }, { name: 'Gestión vehicular', slug: 'gestion-vehicular' }, { name: 'Habilitaciones', slug: 'habilitaciones' }], active: true },
      { name: 'Escribano', slug: 'escribano', icon: '✍️', subcategories: [{ name: 'Escrituras', slug: 'escrituras' }, { name: 'Certificaciones', slug: 'certificaciones' }], active: true },
      { name: 'Asesor financiero', slug: 'asesor-financiero', icon: '💰', subcategories: [{ name: 'Inversiones', slug: 'inversiones' }, { name: 'Planificación financiera', slug: 'planificacion-financiera' }], active: true },
      { name: 'Agente inmobiliario', slug: 'inmobiliario', icon: '🏡', subcategories: [{ name: 'Alquiler', slug: 'alquiler' }, { name: 'Venta de propiedades', slug: 'venta-propiedades' }], active: true },
      { name: 'Tasador de propiedades', slug: 'tasador', icon: '🏘️', subcategories: [{ name: 'Tasación residencial', slug: 'tasacion-residencial' }, { name: 'Tasación comercial', slug: 'tasacion-comercial' }], active: true },
      { name: 'Técnico en calefacción', slug: 'calefaccion', icon: '♨️', subcategories: [{ name: 'Radiadores', slug: 'radiadores' }, { name: 'Piso radiante', slug: 'piso-radiante' }, { name: 'Calderas', slug: 'calderas' }], active: true },
      { name: 'Instalación de domótica', slug: 'domotica', icon: '🏠', subcategories: [{ name: 'Automatización del hogar', slug: 'automatizacion-hogar' }, { name: 'Iluminación inteligente', slug: 'iluminacion-inteligente' }], active: true },
      { name: 'Técnico en ascensores', slug: 'ascensores', icon: '🛗', subcategories: [{ name: 'Mantenimiento', slug: 'mantenimiento-ascensor' }, { name: 'Reparación', slug: 'reparacion-ascensor' }], active: true },
      { name: 'Pintura de graffiti / Muralismo', slug: 'muralismo', icon: '🎨', subcategories: [{ name: 'Murales artísticos', slug: 'murales-artisticos' }, { name: 'Graffiti decorativo', slug: 'graffiti-decorativo' }], active: true },
      { name: 'Diseño de jardines', slug: 'paisajismo', icon: '🌳', subcategories: [{ name: 'Paisajismo', slug: 'paisajismo-diseno' }, { name: 'Huerta orgánica', slug: 'huerta-organica' }], active: true },
      { name: 'Control de plagas', slug: 'plagas', icon: '🪲', subcategories: [{ name: 'Termitas', slug: 'termitas' }, { name: 'Roedores', slug: 'roedores' }, { name: 'Insectos voladores', slug: 'insectos-voladores' }], active: true },
      { name: 'Limpieza de tanques de agua', slug: 'tanques-agua', icon: '💧', subcategories: [{ name: 'Tanques domiciliarios', slug: 'tanques-domiciliarios' }, { name: 'Cisternas', slug: 'cisternas' }], active: true },
      { name: 'Reparación de techos', slug: 'reparacion-techos', icon: '🔨', subcategories: [{ name: 'Goteras', slug: 'goteras' }, { name: 'Estructura de techo', slug: 'estructura-techo' }], active: true },
      { name: 'Constructor de piletas', slug: 'construccion-piletas', icon: '🏗️', subcategories: [{ name: 'Piletas de hormigón', slug: 'piletas-hormigon' }, { name: 'Piletas prefabricadas', slug: 'piletas-prefabricadas' }], active: true },
      { name: 'Reparación de bicicletas', slug: 'bicicletas', icon: '🚲', subcategories: [{ name: 'Mecánica de bici', slug: 'mecanica-bici' }, { name: 'Bicicletas eléctricas', slug: 'bicicletas-electricas' }], active: true },
      { name: 'Técnico de motos', slug: 'motos', icon: '🏍️', subcategories: [{ name: 'Mecánica de motos', slug: 'mecanica-motos' }, { name: 'Electricidad de motos', slug: 'electricidad-motos' }], active: true },
      { name: 'Lavandería a domicilio', slug: 'lavanderia', icon: '👕', subcategories: [{ name: 'Lavado y planchado', slug: 'lavado-planchado' }, { name: 'Tintorería', slug: 'tintoreria' }], active: true },
      { name: 'Costurera / Modista', slug: 'costura', icon: '🧵', subcategories: [{ name: 'Arreglos de ropa', slug: 'arreglos-ropa' }, { name: 'Confección a medida', slug: 'confeccion-medida' }], active: true },
      { name: 'Zapatero', slug: 'zapatero', icon: '👟', subcategories: [{ name: 'Reparación de calzado', slug: 'reparacion-calzado' }, { name: 'Teñido de zapatos', slug: 'tenido-zapatos' }], active: true },
      { name: 'Relojero', slug: 'relojero', icon: '⌚', subcategories: [{ name: 'Reparación de relojes', slug: 'reparacion-relojes' }, { name: 'Cambio de baterías', slug: 'cambio-baterias' }], active: true },
      // ── NUEVAS 300 ──────────────────────────────────────────
      // Salud y bienestar
      { name: 'Kinesiólogo', slug: 'kinesiologo', icon: '💪', subcategories: [{ name: 'Rehabilitación', slug: 'rehabilitacion' }, { name: 'Kinesiología deportiva', slug: 'kinesiologia-deportiva' }, { name: 'Kinesiología respiratoria', slug: 'kinesiologia-respiratoria' }], active: true },
      { name: 'Psicólogo', slug: 'psicologo', icon: '🧠', subcategories: [{ name: 'Terapia individual', slug: 'terapia-individual' }, { name: 'Terapia de pareja', slug: 'terapia-pareja' }, { name: 'Psicología infantil', slug: 'psicologia-infantil' }], active: true },
      { name: 'Nutricionista', slug: 'nutricionista', icon: '🥗', subcategories: [{ name: 'Nutrición deportiva', slug: 'nutricion-deportiva' }, { name: 'Nutrición clínica', slug: 'nutricion-clinica' }, { name: 'Nutrición infantil', slug: 'nutricion-infantil' }], active: true },
      { name: 'Fonoaudiólogo', slug: 'fonoaudiologo', icon: '🗣️', subcategories: [{ name: 'Trastornos del habla', slug: 'trastornos-habla' }, { name: 'Voz profesional', slug: 'voz-profesional' }], active: true },
      { name: 'Terapeuta ocupacional', slug: 'terapeuta-ocupacional', icon: '🖐️', subcategories: [{ name: 'Adultos mayores', slug: 'to-adultos' }, { name: 'Niños con necesidades especiales', slug: 'to-ninos' }], active: true },
      { name: 'Optometrista', slug: 'optometrista', icon: '👁️', subcategories: [{ name: 'Examen visual', slug: 'examen-visual' }, { name: 'Lentes de contacto', slug: 'lentes-contacto' }], active: true },
      { name: 'Homeópata', slug: 'homeopata', icon: '🌿', subcategories: [{ name: 'Homeopatía clásica', slug: 'homeopatia-clasica' }, { name: 'Fitoterapia', slug: 'fitoterapia' }], active: true },
      { name: 'Acupunturista', slug: 'acupuntura', icon: '📍', subcategories: [{ name: 'Acupuntura tradicional', slug: 'acupuntura-tradicional' }, { name: 'Auriculoterapia', slug: 'auriculoterapia' }], active: true },
      { name: 'Quiropráctico', slug: 'quiropractico', icon: '🦴', subcategories: [{ name: 'Ajuste cervical', slug: 'ajuste-cervical' }, { name: 'Columna vertebral', slug: 'columna-vertebral' }], active: true },
      { name: 'Podólogo', slug: 'podologo', icon: '🦶', subcategories: [{ name: 'Podología clínica', slug: 'podologia-clinica' }, { name: 'Podología deportiva', slug: 'podologia-deportiva' }], active: true },
      { name: 'Logopeda', slug: 'logopeda', icon: '💬', subcategories: [{ name: 'Dislexia', slug: 'dislexia' }, { name: 'Disfemia', slug: 'disfemia' }], active: true },
      { name: 'Médico laboral', slug: 'medico-laboral', icon: '🏥', subcategories: [{ name: 'Exámenes preocupacionales', slug: 'preocupacional' }, { name: 'Certificados médicos', slug: 'certificados-medicos' }], active: true },
      { name: 'Obstetra / Partera', slug: 'partera', icon: '👼', subcategories: [{ name: 'Control prenatal', slug: 'control-prenatal' }, { name: 'Parto en casa', slug: 'parto-casa' }], active: true },
      { name: 'Terapista en ABA', slug: 'terapia-aba', icon: '🧩', subcategories: [{ name: 'TEA', slug: 'tea' }, { name: 'Trastornos del desarrollo', slug: 'trastornos-desarrollo' }], active: true },
      { name: 'Coaching ontológico', slug: 'coaching', icon: '🎯', subcategories: [{ name: 'Coach de vida', slug: 'coach-vida' }, { name: 'Coach ejecutivo', slug: 'coach-ejecutivo' }], active: true },
      { name: 'Médico deportivo', slug: 'medico-deportivo', icon: '🏃', subcategories: [{ name: 'Lesiones deportivas', slug: 'lesiones-deportivas' }, { name: 'Evaluación física', slug: 'evaluacion-fisica' }], active: true },
      // Belleza y estética
      { name: 'Peluquero', slug: 'peluquero', icon: '✂️', subcategories: [{ name: 'Corte de cabello', slug: 'corte-cabello' }, { name: 'Coloración', slug: 'coloracion' }, { name: 'Alisado y keratina', slug: 'alisado-keratina' }], active: true },
      { name: 'Esteticista', slug: 'esteticista', icon: '💅', subcategories: [{ name: 'Limpieza facial', slug: 'limpieza-facial' }, { name: 'Depilación', slug: 'depilacion' }, { name: 'Uñas acrílicas', slug: 'unas-acrilicas' }], active: true },
      { name: 'Barbero', slug: 'barbero', icon: '🪒', subcategories: [{ name: 'Corte y afeitado', slug: 'corte-afeitado' }, { name: 'Arreglo de barba', slug: 'arreglo-barba' }], active: true },
      { name: 'Tatuador', slug: 'tatuador', icon: '🖊️', subcategories: [{ name: 'Tatuajes realistas', slug: 'tatuajes-realistas' }, { name: 'Tatuajes geométricos', slug: 'tatuajes-geometricos' }, { name: 'Tatuajes acuarela', slug: 'tatuajes-acuarela' }], active: true },
      { name: 'Piercing', slug: 'piercing', icon: '💎', subcategories: [{ name: 'Piercing corporal', slug: 'piercing-corporal' }, { name: 'Piercing facial', slug: 'piercing-facial' }], active: true },
      { name: 'Depilación láser', slug: 'depilacion-laser', icon: '⚡', subcategories: [{ name: 'Cuerpo completo', slug: 'depilacion-cuerpo' }, { name: 'Facial', slug: 'depilacion-facial-laser' }], active: true },
      { name: 'Micropigmentación', slug: 'micropigmentacion', icon: '✏️', subcategories: [{ name: 'Cejas', slug: 'micropigmentacion-cejas' }, { name: 'Labios', slug: 'micropigmentacion-labios' }, { name: 'Scalp', slug: 'micropigmentacion-scalp' }], active: true },
      { name: 'Extensiones de cabello', slug: 'extensiones-cabello', icon: '💇', subcategories: [{ name: 'Extensiones naturales', slug: 'extensiones-naturales' }, { name: 'Extensiones sintéticas', slug: 'extensiones-sinteticas' }], active: true },
      { name: 'Bronceado sin sol', slug: 'bronceado', icon: '🌞', subcategories: [{ name: 'Autobronceante', slug: 'autobronceante' }, { name: 'Cama solar', slug: 'cama-solar' }], active: true },
      { name: 'Diseño de cejas', slug: 'diseno-cejas', icon: '👁️', subcategories: [{ name: 'Henna de cejas', slug: 'henna-cejas' }, { name: 'Laminado de cejas', slug: 'laminado-cejas' }], active: true },
      { name: 'Uñas gel / semipermanente', slug: 'unas-gel', icon: '💅', subcategories: [{ name: 'Nail art', slug: 'nail-art' }, { name: 'Uñas esculpidas', slug: 'unas-esculpidas' }], active: true },
      { name: 'Spa a domicilio', slug: 'spa-domicilio', icon: '🛁', subcategories: [{ name: 'Circuito spa', slug: 'circuito-spa' }, { name: 'Exfoliación corporal', slug: 'exfoliacion-corporal' }], active: true },
      // Tecnología y sistemas
      { name: 'Técnico en PC', slug: 'tecnico-pc', icon: '💻', subcategories: [{ name: 'Reparación de hardware', slug: 'reparacion-hardware' }, { name: 'Instalación de software', slug: 'instalacion-software' }, { name: 'Virus y malware', slug: 'virus-malware' }], active: true },
      { name: 'Redes y WiFi', slug: 'redes-wifi', icon: '📶', subcategories: [{ name: 'Configuración de router', slug: 'config-router' }, { name: 'Redes empresariales', slug: 'redes-empresariales' }], active: true },
      { name: 'Programador web', slug: 'programador-web', icon: '🌐', subcategories: [{ name: 'Frontend', slug: 'frontend' }, { name: 'Backend', slug: 'backend' }, { name: 'WordPress', slug: 'wordpress' }], active: true },
      { name: 'Desarrollador de apps', slug: 'desarrollador-apps', icon: '📱', subcategories: [{ name: 'Android', slug: 'android' }, { name: 'iOS', slug: 'ios' }, { name: 'App híbrida', slug: 'app-hibrida' }], active: true },
      { name: 'Diseñador gráfico', slug: 'disenador-grafico', icon: '🎨', subcategories: [{ name: 'Identidad visual', slug: 'identidad-visual' }, { name: 'Diseño editorial', slug: 'diseno-editorial' }, { name: 'Packaging', slug: 'packaging' }], active: true },
      { name: 'Community manager', slug: 'community-manager', icon: '📱', subcategories: [{ name: 'Instagram y Facebook', slug: 'ig-fb' }, { name: 'TikTok', slug: 'tiktok' }, { name: 'LinkedIn', slug: 'linkedin' }], active: true },
      { name: 'Diseñador UX/UI', slug: 'ux-ui', icon: '🖥️', subcategories: [{ name: 'Diseño de interfaces', slug: 'diseno-interfaces' }, { name: 'Prototipado', slug: 'prototipado' }], active: true },
      { name: 'SEO / Posicionamiento web', slug: 'seo', icon: '🔍', subcategories: [{ name: 'SEO on-page', slug: 'seo-onpage' }, { name: 'Link building', slug: 'link-building' }], active: true },
      { name: 'Soporte IT empresarial', slug: 'soporte-it', icon: '🖥️', subcategories: [{ name: 'Mesa de ayuda', slug: 'mesa-ayuda' }, { name: 'Mantenimiento preventivo', slug: 'mantenimiento-it' }], active: true },
      { name: 'Técnico en impresoras', slug: 'impresoras', icon: '🖨️', subcategories: [{ name: 'Reparación de impresoras', slug: 'reparacion-impresoras' }, { name: 'Recarga de tóner', slug: 'recarga-toner' }], active: true },
      { name: 'Instalación de TV y home theater', slug: 'home-theater', icon: '📺', subcategories: [{ name: 'Montaje de TV', slug: 'montaje-tv' }, { name: 'Configuración de sonido', slug: 'config-sonido' }], active: true },
      { name: 'Técnico en celulares', slug: 'celulares', icon: '📲', subcategories: [{ name: 'Cambio de pantalla', slug: 'cambio-pantalla' }, { name: 'Cambio de batería', slug: 'cambio-bateria-cel' }, { name: 'Recuperación de datos', slug: 'recuperacion-datos' }], active: true },
      { name: 'Editor de video', slug: 'editor-video', icon: '🎞️', subcategories: [{ name: 'Edición para redes', slug: 'edicion-redes' }, { name: 'Documentales', slug: 'documentales' }, { name: 'Motion graphics', slug: 'motion-graphics' }], active: true },
      { name: 'Diseñador 3D', slug: 'diseno-3d', icon: '📐', subcategories: [{ name: 'Modelado 3D', slug: 'modelado-3d' }, { name: 'Impresión 3D', slug: 'impresion-3d' }, { name: 'Render arquitectónico', slug: 'render-arq' }], active: true },
      { name: 'Copywriter', slug: 'copywriter', icon: '✍️', subcategories: [{ name: 'Contenido web', slug: 'contenido-web' }, { name: 'Email marketing', slug: 'email-marketing' }, { name: 'Guiones', slug: 'guiones' }], active: true },
      { name: 'Analista de datos', slug: 'analista-datos', icon: '📊', subcategories: [{ name: 'Business intelligence', slug: 'bi' }, { name: 'Dashboard y reportes', slug: 'dashboards' }], active: true },
      { name: 'Administrador de servidores', slug: 'admin-servidores', icon: '🖧', subcategories: [{ name: 'Linux / Windows Server', slug: 'linux-winserver' }, { name: 'Cloud (AWS/GCP)', slug: 'cloud' }], active: true },
      { name: 'Fotógrafo publicitario', slug: 'fotografo-publicitario', icon: '📷', subcategories: [{ name: 'Producto', slug: 'foto-producto' }, { name: 'Moda', slug: 'foto-moda' }, { name: 'Gastronomía', slug: 'foto-gastronomia' }], active: true },
      // Construcción y reformas
      { name: 'Electricista', slug: 'electricista', icon: '⚡', subcategories: [{ name: 'Instalaciones residenciales', slug: 'inst-residencial' }, { name: 'Tableros y disyuntores', slug: 'tableros' }, { name: 'Iluminación', slug: 'iluminacion' }], active: true },
      { name: 'Plomero', slug: 'plomero', icon: '🔧', subcategories: [{ name: 'Pérdidas y cañerías', slug: 'perdidas-caneria' }, { name: 'Instalación sanitaria', slug: 'inst-sanitaria' }, { name: 'Termotanque', slug: 'termotanque' }], active: true },
      { name: 'Gasista matriculado', slug: 'gasista', icon: '🔥', subcategories: [{ name: 'Instalación de gas natural', slug: 'gas-natural' }, { name: 'Calderas y calefones', slug: 'calderas-calefones' }, { name: 'Certificado de gas', slug: 'certificado-gas' }], active: true },
      { name: 'Albañil', slug: 'albanil', icon: '🧱', subcategories: [{ name: 'Ampliaciones', slug: 'ampliaciones' }, { name: 'Revoques', slug: 'revoques' }, { name: 'Contrapisos', slug: 'contrapisos' }], active: true },
      { name: 'Pintor de obra', slug: 'pintor', icon: '🖌️', subcategories: [{ name: 'Pintura interior', slug: 'pintura-interior' }, { name: 'Pintura exterior', slug: 'pintura-exterior' }, { name: 'Pintura texturada', slug: 'pintura-texturada' }], active: true },
      { name: 'Carpintero', slug: 'carpintero', icon: '🪚', subcategories: [{ name: 'Muebles a medida', slug: 'muebles-medida' }, { name: 'Restauración de muebles', slug: 'restauracion-muebles' }, { name: 'Deck de madera', slug: 'deck-madera' }], active: true },
      { name: 'Herrero', slug: 'herrero', icon: '⚒️', subcategories: [{ name: 'Rejas y portones', slug: 'rejas-portones' }, { name: 'Escaleras metálicas', slug: 'escaleras-metal' }], active: true },
      { name: 'Cerrajero', slug: 'cerrajero', icon: '🔑', subcategories: [{ name: 'Apertura de puertas', slug: 'apertura-puertas' }, { name: 'Cambio de cerradura', slug: 'cambio-cerradura' }, { name: 'Caja fuerte', slug: 'caja-fuerte' }], active: true },
      { name: 'Vidriero', slug: 'vidriero', icon: '🪟', subcategories: [{ name: 'Vidrios simples', slug: 'vidrios-simples' }, { name: 'Vidrios templados', slug: 'vidrios-templados' }, { name: 'DVH', slug: 'dvh' }], active: true },
      { name: 'Yesero', slug: 'yesero', icon: '🏚️', subcategories: [{ name: 'Durlock', slug: 'durlock' }, { name: 'Cielorrasos', slug: 'cielorrasos' }, { name: 'Tabiques', slug: 'tabiques' }], active: true },
      { name: 'Colocador de aberturas de aluminio', slug: 'aluminio', icon: '🔩', subcategories: [{ name: 'Ventanas de aluminio', slug: 'ventanas-aluminio' }, { name: 'Puertas de aluminio', slug: 'puertas-aluminio' }], active: true },
      { name: 'Demolición y excavación', slug: 'demolicion', icon: '⛏️', subcategories: [{ name: 'Demolición parcial', slug: 'demolicion-parcial' }, { name: 'Excavación manual', slug: 'excavacion-manual' }], active: true },
      { name: 'Arquitecto', slug: 'arquitecto', icon: '📐', subcategories: [{ name: 'Diseño de planos', slug: 'diseno-planos' }, { name: 'Dirección de obra', slug: 'direccion-obra' }, { name: 'Reformas integrales', slug: 'reformas-integrales' }], active: true },
      { name: 'Ingeniero civil', slug: 'ingeniero-civil', icon: '🏗️', subcategories: [{ name: 'Cálculo estructural', slug: 'calculo-estructural' }, { name: 'Inspección de obras', slug: 'inspeccion-obras' }], active: true },
      { name: 'Instalador de aire acondicionado', slug: 'aire-acondicionado', icon: '❄️', subcategories: [{ name: 'Split residencial', slug: 'split-residencial' }, { name: 'Central y ductos', slug: 'central-ductos' }, { name: 'Mantenimiento de AC', slug: 'mantenimiento-ac' }], active: true },
      { name: 'Fumigador', slug: 'fumigador', icon: '🐛', subcategories: [{ name: 'Desinfección', slug: 'desinfeccion' }, { name: 'Desratización', slug: 'desratizacion' }, { name: 'Desinsectación', slug: 'desinsectacion' }], active: true },
      { name: 'Limpieza de hogar', slug: 'limpieza', icon: '🧹', subcategories: [{ name: 'Limpieza regular', slug: 'limpieza-regular' }, { name: 'Limpieza profunda', slug: 'limpieza-profunda' }, { name: 'Post obra', slug: 'post-obra' }], active: true },
      { name: 'Limpieza de alfombras y tapizados', slug: 'limpieza-alfombras', icon: '🧽', subcategories: [{ name: 'Alfombras', slug: 'alfombras' }, { name: 'Tapizados de autos', slug: 'tapizados-autos' }, { name: 'Sillones', slug: 'sillones' }], active: true },
      { name: 'Jardinero', slug: 'jardinero', icon: '🌿', subcategories: [{ name: 'Corte de pasto', slug: 'corte-pasto' }, { name: 'Poda de árboles', slug: 'poda-arboles' }, { name: 'Mantenimiento de jardín', slug: 'mant-jardin' }], active: true },
      { name: 'Tapicero', slug: 'tapicero', icon: '🪑', subcategories: [{ name: 'Tapizado de muebles', slug: 'tapizado-muebles' }, { name: 'Tapizado automotor', slug: 'tapizado-automotor' }], active: true },
      { name: 'Instalador de cielorrasos', slug: 'cielorrasos', icon: '🏠', subcategories: [{ name: 'Cielorraso de yeso', slug: 'cielorraso-yeso' }, { name: 'Cielorraso de PVC', slug: 'cielorraso-pvc' }], active: true },
      { name: 'Reparación de muebles', slug: 'reparacion-muebles', icon: '🪑', subcategories: [{ name: 'Pintura de muebles', slug: 'pintura-muebles' }, { name: 'Reparación estructural', slug: 'reparacion-estructural-mueble' }], active: true },
      { name: 'Instalador de rejas', slug: 'rejas', icon: '🔒', subcategories: [{ name: 'Rejas de seguridad', slug: 'rejas-seguridad' }, { name: 'Rejas decorativas', slug: 'rejas-decorativas' }], active: true },
      // Educación y clases
      { name: 'Profesor de música', slug: 'musica', icon: '🎵', subcategories: [{ name: 'Guitarra', slug: 'guitarra' }, { name: 'Piano', slug: 'piano' }, { name: 'Canto', slug: 'canto' }], active: true },
      { name: 'Profesor de danza', slug: 'danza', icon: '💃', subcategories: [{ name: 'Folklore', slug: 'folklore' }, { name: 'Tango', slug: 'tango' }, { name: 'Salsa y bachata', slug: 'salsa-bachata' }], active: true },
      { name: 'Profesor de dibujo y pintura', slug: 'dibujo-pintura', icon: '🖌️', subcategories: [{ name: 'Dibujo técnico', slug: 'dibujo-tecnico' }, { name: 'Acuarela', slug: 'acuarela' }, { name: 'Óleo', slug: 'oleo' }], active: true },
      { name: 'Clases de teatro', slug: 'teatro', icon: '🎭', subcategories: [{ name: 'Teatro adultos', slug: 'teatro-adultos' }, { name: 'Teatro infantil', slug: 'teatro-infantil' }], active: true },
      { name: 'Clases de fotografía', slug: 'clases-fotografia', icon: '📷', subcategories: [{ name: 'Fotografía básica', slug: 'foto-basica' }, { name: 'Edición fotográfica', slug: 'edicion-foto' }], active: true },
      { name: 'Clases de cocina', slug: 'clases-cocina', icon: '👨‍🍳', subcategories: [{ name: 'Cocina italiana', slug: 'cocina-italiana' }, { name: 'Cocina vegana', slug: 'cocina-vegana' }, { name: 'Panadería', slug: 'panaderia' }], active: true },
      { name: 'Clases de informática', slug: 'clases-informatica', icon: '💻', subcategories: [{ name: 'Excel básico y avanzado', slug: 'excel' }, { name: 'Office completo', slug: 'office' }, { name: 'Redes sociales', slug: 'rs-mayores' }], active: true },
      { name: 'Profesor de matemáticas', slug: 'matematicas', icon: '📐', subcategories: [{ name: 'Primaria', slug: 'mate-primaria' }, { name: 'Secundaria', slug: 'mate-secundaria' }, { name: 'Universitaria', slug: 'mate-universitaria' }], active: true },
      { name: 'Profesor de física', slug: 'fisica', icon: '⚗️', subcategories: [{ name: 'Secundaria', slug: 'fisica-secundaria' }, { name: 'Universitaria', slug: 'fisica-universitaria' }], active: true },
      { name: 'Profesor de química', slug: 'quimica', icon: '🧪', subcategories: [{ name: 'Secundaria', slug: 'quimica-secundaria' }, { name: 'Universitaria', slug: 'quimica-universitaria' }], active: true },
      { name: 'Clases de programación', slug: 'clases-programacion', icon: '👨‍💻', subcategories: [{ name: 'Python', slug: 'python' }, { name: 'JavaScript', slug: 'javascript' }, { name: 'Programación para niños', slug: 'prog-ninos' }], active: true },
      { name: 'Clases de ajedrez', slug: 'ajedrez', icon: '♟️', subcategories: [{ name: 'Ajedrez para principiantes', slug: 'ajedrez-principiantes' }, { name: 'Competición', slug: 'ajedrez-competicion' }], active: true },
      { name: 'Clases de fútbol', slug: 'futbol', icon: '⚽', subcategories: [{ name: 'Escuelita de fútbol', slug: 'escuelita-futbol' }, { name: 'Técnica individual', slug: 'tecnica-futbol' }], active: true },
      { name: 'Clases de tenis', slug: 'tenis', icon: '🎾', subcategories: [{ name: 'Tenis iniciación', slug: 'tenis-iniciacion' }, { name: 'Tenis avanzado', slug: 'tenis-avanzado' }], active: true },
      { name: 'Clases de básquet', slug: 'basquet', icon: '🏀', subcategories: [{ name: 'Básquet infantil', slug: 'basquet-infantil' }, { name: 'Técnica de tiro', slug: 'tecnica-tiro' }], active: true },
      { name: 'Clases de natación avanzada', slug: 'natacion-avanzada', icon: '🏊', subcategories: [{ name: 'Competición', slug: 'natacion-competicion' }, { name: 'Natación artística', slug: 'natacion-artistica' }], active: true },
      { name: 'Clases de equitación', slug: 'equitacion', icon: '🐴', subcategories: [{ name: 'Monta inglesa', slug: 'monta-inglesa' }, { name: 'Monta western', slug: 'monta-western' }], active: true },
      { name: 'Preparación para exámenes', slug: 'preparacion-examenes', icon: '📝', subcategories: [{ name: 'CBT / CBC', slug: 'cbt-cbc' }, { name: 'Exámenes internacionales', slug: 'examenes-internacionales' }], active: true },
      { name: 'Instructor de meditación', slug: 'meditacion-instructor', icon: '🧘', subcategories: [{ name: 'Mindfulness', slug: 'mindfulness' }, { name: 'Meditación guiada', slug: 'meditacion-guiada' }], active: true },
      // Gastronomía y alimentos
      { name: 'Chef a domicilio', slug: 'chef', icon: '👨‍🍳', subcategories: [{ name: 'Cenas íntimas', slug: 'cenas-intimas' }, { name: 'Menú gourmet', slug: 'menu-gourmet' }, { name: 'Asados y parrillas', slug: 'asados' }], active: true },
      { name: 'Catering para empresas', slug: 'catering-empresas', icon: '🍽️', subcategories: [{ name: 'Almuerzos ejecutivos', slug: 'almuerzos-ejecutivos' }, { name: 'Coffee break', slug: 'coffee-break' }], active: true },
      { name: 'Panadero artesanal', slug: 'panadero', icon: '🍞', subcategories: [{ name: 'Pan de masa madre', slug: 'masa-madre' }, { name: 'Facturas y medialunas', slug: 'facturas' }], active: true },
      { name: 'Heladero artesanal', slug: 'heladero', icon: '🍦', subcategories: [{ name: 'Helados a pedido', slug: 'helados-pedido' }, { name: 'Paletas artesanales', slug: 'paletas' }], active: true },
      { name: 'Sommelier', slug: 'sommelier', icon: '🍷', subcategories: [{ name: 'Cata de vinos', slug: 'cata-vinos' }, { name: 'Maridaje', slug: 'maridaje' }], active: true },
      { name: 'Chocolatero', slug: 'chocolatero', icon: '🍫', subcategories: [{ name: 'Bombones artesanales', slug: 'bombones' }, { name: 'Huevos de Pascua', slug: 'huevos-pascua' }], active: true },
      { name: 'Cocinero vegano', slug: 'cocinero-vegano', icon: '🥦', subcategories: [{ name: 'Menús semanales', slug: 'menus-semanales' }, { name: 'Catering vegano', slug: 'catering-vegano' }], active: true },
      { name: 'Asador / Parrillero', slug: 'parrillero', icon: '🔥', subcategories: [{ name: 'Asado para eventos', slug: 'asado-eventos' }, { name: 'Clases de asado', slug: 'clases-asado' }], active: true },
      { name: 'Bizcochero', slug: 'bizcochero', icon: '🥐', subcategories: [{ name: 'Facturas y croissants', slug: 'facturas-croissants' }, { name: 'Tartas y quiches', slug: 'tartas' }], active: true },
      // Transporte y logística
      { name: 'Mudanza local', slug: 'mudanza', icon: '🚚', subcategories: [{ name: 'Mudanza de casa', slug: 'mudanza-casa' }, { name: 'Mudanza de oficina', slug: 'mudanza-oficina' }], active: true },
      { name: 'Remis / Chofer privado', slug: 'remis', icon: '🚖', subcategories: [{ name: 'Traslados al aeropuerto', slug: 'traslado-aeropuerto' }, { name: 'Viajes larga distancia', slug: 'larga-distancia' }], active: true },
      { name: 'Transporte escolar', slug: 'transporte-escolar', icon: '🚐', subcategories: [{ name: 'Jardín y primaria', slug: 'escolar-primaria' }, { name: 'Secundaria', slug: 'escolar-secundaria' }], active: true },
      { name: 'Flete con ayudante', slug: 'flete-ayudante', icon: '🚛', subcategories: [{ name: 'Mudanza asistida', slug: 'mudanza-asistida' }, { name: 'Carga y descarga', slug: 'carga-descarga' }], active: true },
      { name: 'Courier internacional', slug: 'courier', icon: '📦', subcategories: [{ name: 'Compras en USA', slug: 'compras-usa' }, { name: 'Envíos a Europa', slug: 'envios-europa' }], active: true },
      { name: 'Transporte de mascotas', slug: 'transporte-mascotas', icon: '🐾', subcategories: [{ name: 'Traslado al veterinario', slug: 'traslado-vet' }, { name: 'Mudanza con mascotas', slug: 'mudanza-mascotas' }], active: true },
      { name: 'Repartidor con moto propia', slug: 'repartidor-moto', icon: '🏍️', subcategories: [{ name: 'Zona céntrica', slug: 'zona-centrica' }, { name: 'Zona norte/sur', slug: 'zona-norte-sur' }], active: true },
      // Legal, contable y profesional
      { name: 'Contador', slug: 'contador', icon: '🧾', subcategories: [{ name: 'Monotributo', slug: 'monotributo' }, { name: 'Liquidación de sueldos', slug: 'liquidacion-sueldos' }, { name: 'Impuestos', slug: 'impuestos' }], active: true },
      { name: 'Abogado civil', slug: 'abogado-civil', icon: '⚖️', subcategories: [{ name: 'Divorcios', slug: 'divorcios' }, { name: 'Sucesiones', slug: 'sucesiones' }, { name: 'Contratos', slug: 'contratos' }], active: true },
      { name: 'Abogado laboral', slug: 'abogado-laboral', icon: '👔', subcategories: [{ name: 'Despidos', slug: 'despidos' }, { name: 'ART y accidentes', slug: 'art' }], active: true },
      { name: 'Abogado penal', slug: 'abogado-penal', icon: '🔏', subcategories: [{ name: 'Defensa penal', slug: 'defensa-penal' }, { name: 'Delitos informáticos', slug: 'delitos-informaticos' }], active: true },
      { name: 'Asesor impositivo', slug: 'asesor-impositivo', icon: '📑', subcategories: [{ name: 'AFIP y ARBA', slug: 'afip-arba' }, { name: 'Planes de pago', slug: 'planes-pago' }], active: true },
      { name: 'Recursos humanos', slug: 'recursos-humanos', icon: '👥', subcategories: [{ name: 'Selección de personal', slug: 'seleccion-personal' }, { name: 'Capacitación', slug: 'capacitacion-rrhh' }], active: true },
      { name: 'Consultor de negocios', slug: 'consultor-negocios', icon: '📈', subcategories: [{ name: 'Plan de negocios', slug: 'plan-negocios' }, { name: 'Estrategia empresarial', slug: 'estrategia-empresarial' }], active: true },
      { name: 'Marketing digital', slug: 'marketing-digital', icon: '📣', subcategories: [{ name: 'Publicidad en Meta', slug: 'meta-ads' }, { name: 'Google Ads', slug: 'google-ads' }, { name: 'Email marketing', slug: 'email-mkt' }], active: true },
      { name: 'Traductor', slug: 'traductor', icon: '🌐', subcategories: [{ name: 'Inglés - Español', slug: 'ingles-espanol' }, { name: 'Portugués', slug: 'portugues-trad' }, { name: 'Documentos legales', slug: 'docs-legales' }], active: true },
      { name: 'Intérprete', slug: 'interprete', icon: '🗣️', subcategories: [{ name: 'Conferencias', slug: 'conferencias' }, { name: 'Simultáneo', slug: 'simultaneo' }], active: true },
      // Eventos y entretenimiento
      { name: 'DJ para eventos', slug: 'dj', icon: '🎧', subcategories: [{ name: 'DJ para fiestas', slug: 'dj-fiestas' }, { name: 'DJ para casamientos', slug: 'dj-casamientos' }, { name: 'DJ para corporativos', slug: 'dj-corporativos' }], active: true },
      { name: 'Músico para eventos', slug: 'musico-eventos', icon: '🎶', subcategories: [{ name: 'Banda de covers', slug: 'banda-covers' }, { name: 'Solista', slug: 'solista' }, { name: 'Trío de música clásica', slug: 'trio-clasico' }], active: true },
      { name: 'Iluminación para eventos', slug: 'iluminacion-eventos', icon: '💡', subcategories: [{ name: 'Luces de salón', slug: 'luces-salon' }, { name: 'Mapping y efectos', slug: 'mapping' }], active: true },
      { name: 'Sonido para eventos', slug: 'sonido-eventos', icon: '🔊', subcategories: [{ name: 'Equipos de audio', slug: 'equipos-audio' }, { name: 'PA system', slug: 'pa-system' }], active: true },
      { name: 'Maestro de ceremonias', slug: 'mc', icon: '🎤', subcategories: [{ name: 'Casamientos', slug: 'mc-casamiento' }, { name: 'Eventos corporativos', slug: 'mc-corporativo' }], active: true },
      { name: 'Locutor', slug: 'locutor', icon: '🎙️', subcategories: [{ name: 'Locución comercial', slug: 'locucion-comercial' }, { name: 'Voice over', slug: 'voice-over' }], active: true },
      { name: 'Mago para eventos', slug: 'mago', icon: '🎩', subcategories: [{ name: 'Magia infantil', slug: 'magia-infantil' }, { name: 'Magia de salón', slug: 'magia-salon' }], active: true },
      { name: 'Show de humor', slug: 'show-humor', icon: '😂', subcategories: [{ name: 'Stand up', slug: 'stand-up' }, { name: 'Sketches', slug: 'sketches' }], active: true },
      { name: 'Decorador de eventos', slug: 'decorador-eventos', icon: '🎀', subcategories: [{ name: 'Ambientación temática', slug: 'ambientacion-tematica' }, { name: 'Globología', slug: 'globologia' }, { name: 'Centros de mesa', slug: 'centros-mesa' }], active: true },
      { name: 'Florista para eventos', slug: 'florista', icon: '💐', subcategories: [{ name: 'Bouquets de novia', slug: 'bouquets-novia' }, { name: 'Arreglos florales', slug: 'arreglos-florales' }], active: true },
      { name: 'Cabina de fotos', slug: 'cabina-fotos', icon: '📸', subcategories: [{ name: 'Fotomatón', slug: 'fotomaton' }, { name: 'Selfie booth', slug: 'selfie-booth' }], active: true },
      { name: 'Food truck para eventos', slug: 'food-truck', icon: '🚐', subcategories: [{ name: 'Hamburguesas', slug: 'ft-hamburguesas' }, { name: 'Sushi', slug: 'ft-sushi' }, { name: 'Vegano', slug: 'ft-vegano' }], active: true },
      { name: 'Alquiler de vajilla y mobiliario', slug: 'alquiler-vajilla', icon: '🍽️', subcategories: [{ name: 'Vajilla fina', slug: 'vajilla-fina' }, { name: 'Mesas y sillas', slug: 'mesas-sillas' }], active: true },
      { name: 'Alquiler de inflables', slug: 'inflables', icon: '🎈', subcategories: [{ name: 'Inflables para niños', slug: 'inflables-ninos' }, { name: 'Toboganes', slug: 'toboganes' }], active: true },
      { name: 'Shows de ciencia', slug: 'shows-ciencia', icon: '🔬', subcategories: [{ name: 'Experimentos infantiles', slug: 'experimentos-infantiles' }, { name: 'Talleres educativos', slug: 'talleres-educativos' }], active: true },
      // Deportes y fitness
      { name: 'Entrenador de fútbol', slug: 'entrenador-futbol', icon: '⚽', subcategories: [{ name: 'Juveniles', slug: 'futbol-juveniles' }, { name: 'Amateur', slug: 'futbol-amateur' }], active: true },
      { name: 'Instructor de crossfit', slug: 'crossfit', icon: '🏋️', subcategories: [{ name: 'Clases grupales', slug: 'crossfit-grupal' }, { name: 'Clases personales', slug: 'crossfit-personal' }], active: true },
      { name: 'Instructor de spinning', slug: 'spinning', icon: '🚴', subcategories: [{ name: 'Clases indoor', slug: 'spinning-indoor' }, { name: 'Ciclismo outdoor', slug: 'ciclismo-outdoor' }], active: true },
      { name: 'Instructor de artes marciales', slug: 'artes-marciales', icon: '🥋', subcategories: [{ name: 'Karate', slug: 'karate' }, { name: 'Judo', slug: 'judo' }, { name: 'Taekwondo', slug: 'taekwondo' }], active: true },
      { name: 'Instructor de boxeo', slug: 'boxeo', icon: '🥊', subcategories: [{ name: 'Boxeo fitness', slug: 'boxeo-fitness' }, { name: 'Boxeo competitivo', slug: 'boxeo-competitivo' }], active: true },
      { name: 'Instructor de rugby', slug: 'rugby', icon: '🏉', subcategories: [{ name: 'Categorías infantiles', slug: 'rugby-infantil' }, { name: 'Técnica y táctica', slug: 'rugby-tecnica' }], active: true },
      { name: 'Preparador físico', slug: 'preparador-fisico', icon: '🏃', subcategories: [{ name: 'Fútbol', slug: 'prep-futbol' }, { name: 'Atletismo', slug: 'prep-atletismo' }, { name: 'General', slug: 'prep-general' }], active: true },
      { name: 'Corrección postural', slug: 'postura', icon: '🧍', subcategories: [{ name: 'Evaluación postural', slug: 'evaluacion-postural' }, { name: 'Ejercicios correctivos', slug: 'ejercicios-correctivos' }], active: true },
      { name: 'Entrenamiento para maratón', slug: 'maraton', icon: '🏅', subcategories: [{ name: 'Plan de entrenamiento', slug: 'plan-maraton' }, { name: 'Acompañamiento nutricional', slug: 'nutricion-maraton' }], active: true },
      // Hogar y servicios varios
      { name: 'Cuidado de plantas', slug: 'cuidado-plantas', icon: '🌱', subcategories: [{ name: 'Riego y fertilización', slug: 'riego-fertilizacion' }, { name: 'Plantas de interior', slug: 'plantas-interior' }], active: true },
      { name: 'Instalación de portones automáticos', slug: 'portones', icon: '🚗', subcategories: [{ name: 'Portón corredizo', slug: 'porton-corredizo' }, { name: 'Portón levadizo', slug: 'porton-levadizo' }], active: true },
      { name: 'Técnico en lavarropas', slug: 'tecnico-lavarropas', icon: '🫧', subcategories: [{ name: 'Lavarropas de carga frontal', slug: 'carga-frontal' }, { name: 'Lavarropas de carga superior', slug: 'carga-superior' }], active: true },
      { name: 'Técnico en heladeras', slug: 'tecnico-heladera', icon: '🧊', subcategories: [{ name: 'Heladeras domésticas', slug: 'heladera-domestica' }, { name: 'Freezers', slug: 'freezers' }], active: true },
      { name: 'Instalación de termotanque', slug: 'termotanque', icon: '🚿', subcategories: [{ name: 'Termotanque eléctrico', slug: 'termotanque-electrico' }, { name: 'Termotanque a gas', slug: 'termotanque-gas' }], active: true },
      { name: 'Técnico en televisores', slug: 'tecnico-tv', icon: '📺', subcategories: [{ name: 'Smart TV', slug: 'smart-tv' }, { name: 'LED y plasma', slug: 'led-plasma' }], active: true },
      { name: 'Instalación de piletón / jacuzzi', slug: 'jacuzzi', icon: '🛁', subcategories: [{ name: 'Jacuzzi exterior', slug: 'jacuzzi-exterior' }, { name: 'Bañera hidromasaje', slug: 'banera-hidromasaje' }], active: true },
      { name: 'Reparación de sillas y mesas', slug: 'reparacion-sillas', icon: '🪑', subcategories: [{ name: 'Sillas de madera', slug: 'sillas-madera' }, { name: 'Mesas de vidrio', slug: 'mesas-vidrio' }], active: true },
      { name: 'Armado de muebles', slug: 'armado-muebles', icon: '🔨', subcategories: [{ name: 'Muebles planos', slug: 'muebles-planos' }, { name: 'Cocinas modulares', slug: 'cocinas-modulares' }], active: true },
      { name: 'Pintura de aberturas', slug: 'pintura-aberturas', icon: '🖌️', subcategories: [{ name: 'Puertas y ventanas', slug: 'puertas-ventanas' }, { name: 'Rejas y barandas', slug: 'rejas-barandas' }], active: true },
      { name: 'Destape de cañerías', slug: 'destape', icon: '🔧', subcategories: [{ name: 'Destape manual', slug: 'destape-manual' }, { name: 'Destape con cámara', slug: 'destape-camara' }], active: true },
      { name: 'Instalación de calefactores', slug: 'calefactores', icon: '🔥', subcategories: [{ name: 'Calefactor a gas', slug: 'calefactor-gas' }, { name: 'Eléctrico', slug: 'calefactor-electrico' }], active: true },
      { name: 'Servicio de planchado', slug: 'planchado', icon: '👔', subcategories: [{ name: 'Ropa formal', slug: 'planchado-formal' }, { name: 'Ropa de cama', slug: 'planchado-cama' }], active: true },
      { name: 'Cuidado de piletas', slug: 'cuidado-piletas', icon: '🏊', subcategories: [{ name: 'Mantenimiento semanal', slug: 'mantenimiento-pileta' }, { name: 'Tratamiento de agua', slug: 'tratamiento-agua' }], active: true },
      { name: 'Instalación de portero eléctrico', slug: 'portero-electrico', icon: '🔔', subcategories: [{ name: 'Videoportero', slug: 'videoportero' }, { name: 'Portero simple', slug: 'portero-simple' }], active: true },
      { name: 'Instalación de riego automático', slug: 'riego-automatico', icon: '💧', subcategories: [{ name: 'Riego por goteo', slug: 'goteo' }, { name: 'Aspersores', slug: 'aspersores' }], active: true },
      { name: 'Colocación de deck', slug: 'deck', icon: '🪵', subcategories: [{ name: 'Deck de madera natural', slug: 'deck-natural' }, { name: 'Deck sintético', slug: 'deck-sintetico' }], active: true },
      { name: 'Montaje de muebles de cocina', slug: 'cocina-muebles', icon: '🍳', subcategories: [{ name: 'Alacenas', slug: 'alacenas' }, { name: 'Bajo mesada', slug: 'bajo-mesada' }], active: true },
      // Automotor
      { name: 'Mecánico de autos', slug: 'mecanico', icon: '🔩', subcategories: [{ name: 'Service general', slug: 'service-general' }, { name: 'Frenos', slug: 'frenos' }, { name: 'Suspensión', slug: 'suspension' }], active: true },
      { name: 'Electricista automotor', slug: 'electricista-auto', icon: '⚡', subcategories: [{ name: 'Alarmas y audio', slug: 'alarmas-audio' }, { name: 'Instalación eléctrica', slug: 'inst-electrica-auto' }], active: true },
      { name: 'Gomero / Vulcanizador', slug: 'gomero', icon: '🔄', subcategories: [{ name: 'Cambio de cubiertas', slug: 'cambio-cubiertas' }, { name: 'Reparación de pinchazos', slug: 'pinchazo' }], active: true },
      { name: 'Instalación de GNC', slug: 'gnc', icon: '⛽', subcategories: [{ name: 'Instalación nueva', slug: 'gnc-nueva' }, { name: 'Revisión y carga', slug: 'gnc-revision' }], active: true },
      { name: 'Tapicería automotor', slug: 'tapiceria-auto', icon: '🪑', subcategories: [{ name: 'Butacas y techo', slug: 'butacas-techo' }, { name: 'Alfombras de auto', slug: 'alfombras-auto' }], active: true },
      { name: 'Rectificación de motor', slug: 'rectificacion', icon: '⚙️', subcategories: [{ name: 'Rectificado de cabezas', slug: 'cabezas-motor' }, { name: 'Cigüeñal', slug: 'ciguenial' }], active: true },
      { name: 'Vidrios de autos', slug: 'vidrios-auto', icon: '🪟', subcategories: [{ name: 'Parabrisas', slug: 'parabrisas' }, { name: 'Vidrios laterales', slug: 'vidrios-laterales' }], active: true },
      { name: 'Auxilio mecánico', slug: 'auxilio-mecanico', icon: '🚨', subcategories: [{ name: 'Batería y arranque', slug: 'bateria-arranque' }, { name: 'Remolque', slug: 'remolque' }], active: true },
      { name: 'Taller de chapa y pintura', slug: 'chapa-pintura-taller', icon: '🚘', subcategories: [{ name: 'Abolladuras', slug: 'abolladuras' }, { name: 'Pintura parcial', slug: 'pintura-parcial' }], active: true },
      { name: 'Instalación de alarma para autos', slug: 'alarma-auto', icon: '🚨', subcategories: [{ name: 'Alarma con GPS', slug: 'alarma-gps' }, { name: 'Inmovilizador', slug: 'inmovilizador' }], active: true },
      // Arte y cultura
      { name: 'Escultor', slug: 'escultor', icon: '🗿', subcategories: [{ name: 'Escultura en madera', slug: 'escultura-madera' }, { name: 'Escultura en mármol', slug: 'escultura-marmol' }], active: true },
      { name: 'Ceramista / Alfarero', slug: 'ceramista', icon: '🏺', subcategories: [{ name: 'Torno de alfarería', slug: 'torno-alfareria' }, { name: 'Cerámica decorativa', slug: 'ceramica-decorativa' }], active: true },
      { name: 'Ilustrador', slug: 'ilustrador', icon: '✏️', subcategories: [{ name: 'Ilustración editorial', slug: 'ilustracion-editorial' }, { name: 'Ilustración digital', slug: 'ilustracion-digital' }], active: true },
      { name: 'Artesano en cuero', slug: 'cuero', icon: '👜', subcategories: [{ name: 'Cinturones y billeteras', slug: 'cinturones-billeteras' }, { name: 'Marroquinería', slug: 'marroquineria' }], active: true },
      { name: 'Tejedor / Tejedora', slug: 'tejedor', icon: '🧶', subcategories: [{ name: 'Crochet', slug: 'crochet' }, { name: 'Telar', slug: 'telar' }], active: true },
      { name: 'Joyero artesanal', slug: 'joyero', icon: '💍', subcategories: [{ name: 'Anillos y pulseras', slug: 'anillos-pulseras' }, { name: 'Plata y oro', slug: 'plata-oro' }], active: true },
      { name: 'Lutier', slug: 'lutier', icon: '🎸', subcategories: [{ name: 'Reparación de guitarras', slug: 'reparacion-guitarras' }, { name: 'Fabricación de instrumentos', slug: 'fabricacion-instrumentos' }], active: true },
      { name: 'Restaurador de arte', slug: 'restaurador-arte', icon: '🖼️', subcategories: [{ name: 'Pintura', slug: 'restauracion-pintura' }, { name: 'Esculturas', slug: 'restauracion-esculturas' }], active: true },
      { name: 'Encuadernador', slug: 'encuadernador', icon: '📚', subcategories: [{ name: 'Encuadernación artesanal', slug: 'encuad-artesanal' }, { name: 'Restauración de libros', slug: 'restauracion-libros' }], active: true },
      // Medio ambiente y sostenibilidad
      { name: 'Recolección de residuos especiales', slug: 'residuos-especiales', icon: '♻️', subcategories: [{ name: 'Electrónicos', slug: 'electronicos-reciclaje' }, { name: 'Pilas y baterías', slug: 'pilas-baterias' }], active: true },
      { name: 'Consultor ambiental', slug: 'consultor-ambiental', icon: '🌎', subcategories: [{ name: 'Evaluación de impacto', slug: 'impacto-ambiental' }, { name: 'Gestión de residuos', slug: 'gestion-residuos' }], active: true },
      { name: 'Instalación de biodigestor', slug: 'biodigestor', icon: '🌱', subcategories: [{ name: 'Doméstico', slug: 'biodigestor-dom' }, { name: 'Industrial', slug: 'biodigestor-ind' }], active: true },
      { name: 'Consultor en eficiencia energética', slug: 'eficiencia-energetica', icon: '💡', subcategories: [{ name: 'Auditoría energética', slug: 'auditoria-energetica' }, { name: 'Certificación de edificios', slug: 'cert-edificios' }], active: true },
      // Servicios para empresas
      { name: 'Limpieza de oficinas', slug: 'limpieza-oficinas', icon: '🏢', subcategories: [{ name: 'Limpieza diaria', slug: 'limpieza-diaria-of' }, { name: 'Limpieza profunda', slug: 'limpieza-profunda-of' }], active: true },
      { name: 'Mensajería empresarial', slug: 'mensajeria-empresarial', icon: '📬', subcategories: [{ name: 'Distribución de correspondencia', slug: 'correspondencia' }, { name: 'Documentos urgentes', slug: 'docs-urgentes' }], active: true },
      { name: 'Asistente virtual', slug: 'asistente-virtual', icon: '🤖', subcategories: [{ name: 'Administración remota', slug: 'admin-remota' }, { name: 'Soporte al cliente', slug: 'soporte-cliente' }], active: true },
      { name: 'Transcripción de audio', slug: 'transcripcion', icon: '📝', subcategories: [{ name: 'Reuniones y conferencias', slug: 'transcripcion-reuniones' }, { name: 'Entrevistas', slug: 'transcripcion-entrevistas' }], active: true },
      { name: 'Fotografía inmobiliaria', slug: 'foto-inmobiliaria', icon: '🏠', subcategories: [{ name: 'Exterior e interior', slug: 'foto-prop' }, { name: 'Drone inmobiliario', slug: 'drone-inmobiliario' }], active: true },
      { name: 'Tour virtual 360°', slug: 'tour-virtual', icon: '🌐', subcategories: [{ name: 'Propiedades', slug: 'tour-propiedades' }, { name: 'Locales comerciales', slug: 'tour-locales' }], active: true },
      { name: 'Consultor de imagen personal', slug: 'imagen-personal', icon: '👔', subcategories: [{ name: 'Asesoría de vestuario', slug: 'asesoria-vestuario' }, { name: 'Personal shopper', slug: 'personal-shopper' }], active: true },
      { name: 'Diseñador de stands', slug: 'stands', icon: '🏪', subcategories: [{ name: 'Ferias y exposiciones', slug: 'ferias' }, { name: 'Stands modulares', slug: 'stands-modulares' }], active: true },
      { name: 'Agencia de modelos', slug: 'modelos', icon: '💃', subcategories: [{ name: 'Modelos para publicidad', slug: 'modelos-publicidad' }, { name: 'Promotoras', slug: 'promotoras' }], active: true },
      // Servicios especializados varios
      { name: 'Instructor de manejo defensivo', slug: 'manejo-defensivo', icon: '🛡️', subcategories: [{ name: 'Conductores particulares', slug: 'conductores-part' }, { name: 'Conductores profesionales', slug: 'conductores-prof' }], active: true },
      { name: 'Asesor en seguros', slug: 'seguros', icon: '📋', subcategories: [{ name: 'Seguros de auto', slug: 'seguros-auto' }, { name: 'Seguros de hogar', slug: 'seguros-hogar' }, { name: 'Seguros de vida', slug: 'seguros-vida' }], active: true },
      { name: 'Servicio de acompañamiento', slug: 'acompanamiento', icon: '🤝', subcategories: [{ name: 'Acompañamiento médico', slug: 'acomp-medico' }, { name: 'Acompañamiento judicial', slug: 'acomp-judicial' }], active: true },
      { name: 'Digitalizador de fotos y VHS', slug: 'digitalizacion', icon: '📼', subcategories: [{ name: 'Digitalización de fotos', slug: 'digit-fotos' }, { name: 'Digitalización de VHS', slug: 'digit-vhs' }], active: true },
      { name: 'Reparación de instrumentos musicales', slug: 'reparacion-instrumentos', icon: '🎸', subcategories: [{ name: 'Cuerdas', slug: 'rep-cuerdas' }, { name: 'Viento', slug: 'rep-viento' }], active: true },
      { name: 'Afinador de pianos', slug: 'afinador-piano', icon: '🎹', subcategories: [{ name: 'Afinación estándar', slug: 'afinacion-estandar' }, { name: 'Restauración de piano', slug: 'restauracion-piano' }], active: true },
      { name: 'Servicio de guardacoches', slug: 'guardacoches', icon: '🅿️', subcategories: [{ name: 'Eventos privados', slug: 'eventos-guardacoches' }, { name: 'Mensuales', slug: 'mensuales-guardacoches' }], active: true },
      { name: 'Instalación de pérgolas', slug: 'pergolas', icon: '🏡', subcategories: [{ name: 'Pérgola de madera', slug: 'pergola-madera' }, { name: 'Pérgola bioclimática', slug: 'pergola-bioclimatica' }], active: true },
      { name: 'Constructor de quinchos', slug: 'quinchos', icon: '🏕️', subcategories: [{ name: 'Quincho de madera', slug: 'quincho-madera' }, { name: 'Quincho de material', slug: 'quincho-material' }], active: true },
      { name: 'Instructor de supervivencia', slug: 'supervivencia', icon: '🏕️', subcategories: [{ name: 'Bushcraft', slug: 'bushcraft' }, { name: 'Primeros auxilios en la naturaleza', slug: 'primeros-auxilios-nat' }], active: true },
      { name: 'Guía de turismo', slug: 'guia-turismo', icon: '🗺️', subcategories: [{ name: 'City tour', slug: 'city-tour' }, { name: 'Ecoturismo', slug: 'ecoturismo' }], active: true },
      { name: 'Operador de drones', slug: 'drones', icon: '🚁', subcategories: [{ name: 'Filmación aérea', slug: 'filmacion-aerea' }, { name: 'Inspección técnica', slug: 'inspeccion-drone' }], active: true },
      { name: 'Instalación de enchufes y llaves', slug: 'enchufes', icon: '🔌', subcategories: [{ name: 'Enchufes USB', slug: 'enchufes-usb' }, { name: 'Llaves inteligentes', slug: 'llaves-inteligentes' }], active: true },
      { name: 'Reparación de persianas', slug: 'reparacion-persianas', icon: '🪟', subcategories: [{ name: 'Persianas de enrollar', slug: 'persianas-enrollar' }, { name: 'Persianas venecianas', slug: 'persianas-venecianas' }], active: true },
      { name: 'Instalación de paneles acústicos', slug: 'paneles-acusticos', icon: '🔇', subcategories: [{ name: 'Estudios de grabación', slug: 'estudios-grabacion' }, { name: 'Salas de reuniones', slug: 'salas-reuniones' }], active: true },
      { name: 'Consultor gastronómico', slug: 'consultor-gastronomico', icon: '🍴', subcategories: [{ name: 'Diseño de carta', slug: 'diseno-carta' }, { name: 'Gestión de restaurante', slug: 'gestion-restaurante' }], active: true },
      { name: 'Montaje de exposiciones', slug: 'montaje-exposiciones', icon: '🖼️', subcategories: [{ name: 'Galerías de arte', slug: 'galerias-arte' }, { name: 'Museos', slug: 'museos' }], active: true },
      { name: 'Diseñador de packaging', slug: 'packaging-disenador', icon: '📦', subcategories: [{ name: 'Cajas personalizadas', slug: 'cajas-personalizadas' }, { name: 'Etiquetas', slug: 'etiquetas' }], active: true },
      { name: 'Servicio de mudanza interna', slug: 'mudanza-interna', icon: '🏠', subcategories: [{ name: 'Reubicación de muebles', slug: 'reubicacion-muebles' }, { name: 'Traslado dentro del edificio', slug: 'traslado-edificio' }], active: true },
      { name: 'Instalador de pergotex', slug: 'pergotex', icon: '☂️', subcategories: [{ name: 'Toldos corredizos', slug: 'toldos-corredizos' }, { name: 'Toldos fijos', slug: 'toldos-fijos' }], active: true },
      { name: 'Fabricante de muebles de cocina', slug: 'fabricante-cocina', icon: '🍳', subcategories: [{ name: 'Cocinas integrales', slug: 'cocinas-integrales' }, { name: 'Mesadas de granito', slug: 'mesadas-granito' }], active: true },
      { name: 'Instalación de pisos flotantes', slug: 'pisos-flotantes', icon: '🪵', subcategories: [{ name: 'Laminado', slug: 'laminado-flotante' }, { name: 'Vinílico SPC', slug: 'vinilico-spc' }], active: true },
      { name: 'Reparación de heladeras comerciales', slug: 'heladeras-comerciales-rep', icon: '🧊', subcategories: [{ name: 'Heladeras verticales', slug: 'heladeras-verticales' }, { name: 'Heladeras de mostrador', slug: 'heladeras-mostrador' }], active: true },
      { name: 'Instalación de toldos', slug: 'toldos', icon: '⛱️', subcategories: [{ name: 'Toldos de balcón', slug: 'toldos-balcon' }, { name: 'Toldos de terraza', slug: 'toldos-terraza' }], active: true },
      { name: 'Servicio de niñera nocturna', slug: 'ninera-nocturna', icon: '🌙', subcategories: [{ name: 'Recién nacidos', slug: 'ninera-recien-nacido' }, { name: 'Niños de 1 a 5 años', slug: 'ninera-1-5' }], active: true },
      { name: 'Instructor de golf', slug: 'golf', icon: '⛳', subcategories: [{ name: 'Golf iniciación', slug: 'golf-iniciacion' }, { name: 'Golf avanzado', slug: 'golf-avanzado' }], active: true },
      { name: 'Instructor de paddle', slug: 'paddle', icon: '🏓', subcategories: [{ name: 'Paddle adultos', slug: 'paddle-adultos' }, { name: 'Paddle infantil', slug: 'paddle-infantil' }], active: true },
      { name: 'Instructor de surf', slug: 'surf', icon: '🏄', subcategories: [{ name: 'Iniciación al surf', slug: 'surf-iniciacion' }, { name: 'Perfeccionamiento', slug: 'surf-avanzado' }], active: true },
      { name: 'Instructor de escalada', slug: 'escalada', icon: '🧗', subcategories: [{ name: 'Escalada en roca', slug: 'escalada-roca' }, { name: 'Escalada en boulder', slug: 'boulder' }], active: true }, { name: 'Diseñador de interiores', slug: 'disenador-interiores', icon: '🛋️', subcategories: [{ name: 'Diseño residencial', slug: 'diseno-residencial' }, { name: 'Diseño comercial', slug: 'diseno-comercial' }, { name: 'Reformas integrales', slug: 'reformas-integrales-int' }], active: true },
      { name: 'Durlero', slug: 'durlero', icon: '🏗️', subcategories: [{ name: 'Tabiques de durlock', slug: 'tabiques-durlock' }, { name: 'Cielorrasos de durlock', slug: 'cielorrasos-durlock' }, { name: 'Construcción en seco', slug: 'construccion-seco' }], active: true },
      { name: 'Empleada doméstica', slug: 'empleada-domestica', icon: '🏠', subcategories: [{ name: 'Limpieza por horas', slug: 'limpieza-horas' }, { name: 'Limpieza fija', slug: 'limpieza-fija' }, { name: 'Cuidado del hogar', slug: 'cuidado-hogar' }], active: true },
    ];
    let inserted = 0;
    for (const cat of newCats) {
      const exists = await ServiceCategory.findOne({ slug: cat.slug });
      if (!exists) { await ServiceCategory.create(cat); inserted++; }
    }
    res.json({ ok: true, inserted, total: await ServiceCategory.countDocuments() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/activate-all-categories', async (req, res) => {
  try {
    const ServiceCategory = require('../models/servicecategory');
    const result = await ServiceCategory.updateMany({}, { active: true });
    res.json({ ok: true, updated: result.modifiedCount });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;